name: for_all1
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter_blue_plus: ^1.30.4
  permission_handler: ^11.0.1
  vibration: ^1.8.4
  flutter:
    sdk: flutter
    
  provider: ^6.1.0
  cupertino_icons: ^1.0.8
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/artworks.json
    - assets/audio/

